CREATE TABLE Sleeqvehiclecars(
Idxno BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Sleeqcarcode BIGINT NOT NULL UNIQUE,
Vehiclemodel VARCHAR(100) NOT NULL,
Vehiclecapacity VARCHAR(100) NOT NULL,
Vehicleimage VARCHAR(100) NOT NULL,
Fromday VARCHAR(50) NOT NULL,
Today VARCHAR(50) NOT NULL,
Hireprice DECIMAL(10,2) NOT NULL,
Createdby BIGINT NOT NULL DEFAULT 100,
Datecreated DATETIME NOT NULL DEFAULT GETDATE()
)