CREATE TABLE Sleeqcars(
Idxno BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Sleeqcarcode BIGINT NOT NULL UNIQUE,
Sleeqcarimage VARCHAR(MAX) NOT NULL,
Seaters VARCHAR(20) NOT NULL,
Fueltype VARCHAR(100) NOT NULL,
Enginesize VARCHAR(100) NOT NULL,
Createdby BIGINT NOT NULL DEFAULT 100,
Datecreated DATETIME NOT NULL DEFAULT GETDATE()
)
CREATE TABLE Sleeqcarshiredays(
Idxno BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Sleeqcarhiredayscode BIGINT NOT NULL UNIQUE,
Sleeqcarcode BIGINT NOT NULL,
Hirefrom VARCHAR(100) NOT NULL,
Hireto VARCHAR(100) NOT NULL,
Hireprice Decimal(18,2) NOT NULL
)
